// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhNw3mh0T9hZV9vi7uUiJ8AJ9TJAK7bsc',
    appId: '1:822709354560:web:ec890732bf6045cd5e9fa5',
    messagingSenderId: '822709354560',
    projectId: 'water-quality-db-630a8',
    authDomain: 'water-quality-db-630a8.firebaseapp.com',
    databaseURL: 'https://water-quality-db-630a8-default-rtdb.firebaseio.com',
    storageBucket: 'water-quality-db-630a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU5HcUhZuWoSvos7N52b5BM2mvfWE1akc',
    appId: '1:822709354560:android:6eb1bec43bcf0f8f5e9fa5',
    messagingSenderId: '822709354560',
    projectId: 'water-quality-db-630a8',
    databaseURL: 'https://water-quality-db-630a8-default-rtdb.firebaseio.com',
    storageBucket: 'water-quality-db-630a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpm0N1sQ8JL6qNdC4Om8P8tQJIQvnqqCE',
    appId: '1:822709354560:ios:a68c84929d97c07f5e9fa5',
    messagingSenderId: '822709354560',
    projectId: 'water-quality-db-630a8',
    databaseURL: 'https://water-quality-db-630a8-default-rtdb.firebaseio.com',
    storageBucket: 'water-quality-db-630a8.firebasestorage.app',
    iosBundleId: 'com.example.waterQuality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpm0N1sQ8JL6qNdC4Om8P8tQJIQvnqqCE',
    appId: '1:822709354560:ios:a68c84929d97c07f5e9fa5',
    messagingSenderId: '822709354560',
    projectId: 'water-quality-db-630a8',
    databaseURL: 'https://water-quality-db-630a8-default-rtdb.firebaseio.com',
    storageBucket: 'water-quality-db-630a8.firebasestorage.app',
    iosBundleId: 'com.example.waterQuality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhNw3mh0T9hZV9vi7uUiJ8AJ9TJAK7bsc',
    appId: '1:822709354560:web:e0528b28f85992245e9fa5',
    messagingSenderId: '822709354560',
    projectId: 'water-quality-db-630a8',
    authDomain: 'water-quality-db-630a8.firebaseapp.com',
    databaseURL: 'https://water-quality-db-630a8-default-rtdb.firebaseio.com',
    storageBucket: 'water-quality-db-630a8.firebasestorage.app',
  );
}
